apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: myapp-dev
  labels:
    app: myapp
    costcenter: aidevops
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
